### ISSUE TITLE
Declaring pointers to alias types fails.

### ISSUE THREAD

**Issue by schancel** [deadalnix/libd#32]
Following code asserts:  `core.exception.AssertError@libd-llvm/libd/src/d/parser/ambiguous.d(318): Can be a pointer or an expression, or maybe even a declaration. That is bad !`

```D
alias uintptr_t = size_t;
int main()
{
	uint* a; //works
	auto z = cast(uintptr_t*)null; //works
	uintptr_t* b; //Fails

	return 0;
}
```

**Comment by deadalnix** [comment]
This issue was moved to deadalnix/SDC#116
