### ISSUE TITLE
src/d/base/type.d is a blocker to compile sdc under 32bit

### ISSUE THREAD

**Issue by UplinkCoder** [deadalnix/libd#54]
If you try to compile under 32bit the assertion libd-llvm/libd/src/d/base/type.d(24): Error: static assert  "Payload must be the same size as ulong." is triggerd.
I'll try to fix this, but I am not to familiar with that part of the codebase.

**Comment by deadalnix** [comment]
"No description provided."

**Comment by deadalnix** [comment]
from ir types or ast types ?

**Comment by UplinkCoder** [comment]
ir types.
but it does not really matter, as both are pointers.

**Comment by UplinkCoder** [comment]
fixed by #61

**Comment by deadalnix** [comment]
Closing, there is nothing actionable in this bug reprot anyway. It doesn't even mention what the problem is.
